"use client";
import { useEffect, useState } from "react";
import { ArrowRight, BookOpen, Check, HeartHandshake, Leaf, Menu, Mountain, ShieldCheck, Sparkles, Star, Users, X } from "lucide-react";

const money = (value) => new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 }).format(value || 0);
const fallbackTotals = [{ category: "Transportasi sekolah", total: 1865000 }, { category: "Gizi & makan siang", total: 1240000 }, { category: "Peralatan digital & kuota", total: 620000 }];

export default function App() {
  const [packages, setPackages] = useState([]); const [hosts, setHosts] = useState([]); const [totals, setTotals] = useState(fallbackTotals); const [modal, setModal] = useState(null); const [menu, setMenu] = useState(false); const [form, setForm] = useState({ guest_name: "", guest_count: 1, travel_date: "" }); const [notice, setNotice] = useState("");
  useEffect(() => { Promise.all([fetch("/api/packages").then((r) => r.json()), fetch("/api/hosts").then((r) => r.json()), fetch("/api").then((r) => r.json())]).then(([p, h, s]) => { setPackages(p.packages || []); setHosts(h.hosts || []); if (s.totals?.length) setTotals(s.totals); }).catch(() => setNotice("Mode offline: data contoh tetap bisa dijelajahi.")); }, []);
  const book = async (event) => { event.preventDefault(); const result = await fetch("/api/bookings", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, package_id: modal.id }) }).then((r) => r.json()); if (result.booking) { setNotice(`Booking berhasil. ${result.allocations.length} alokasi pendidikan otomatis tercatat.`); setModal(null); } else setNotice(result.error || "Booking belum berhasil."); };
  const totalImpact = totals.reduce((sum, item) => sum + item.total, 0);
  return <main className="min-h-screen bg-[#f7f7f2] text-[#173f3a]">
    <nav className="container mx-auto flex items-center justify-between px-5 py-5"><a href="#top" className="flex items-center gap-2 font-bold tracking-tight"><span className="grid h-9 w-9 place-items-center rounded-full bg-[#e5a94c] text-[#173f3a]"><Mountain size={20} /></span>Mountain<span className="text-[#e29b35]">Harmony</span></a><div className={`${menu ? "flex" : "hidden"} absolute left-0 top-[74px] z-20 w-full flex-col gap-5 bg-[#f7f7f2] px-5 py-5 md:static md:flex md:w-auto md:flex-row md:items-center md:bg-transparent`}><a href="#journeys" onClick={() => setMenu(false)} className="text-sm font-semibold">Pilih perjalanan</a><a href="#impact" onClick={() => setMenu(false)} className="text-sm font-semibold">Lihat dampak</a><a href="#hosts" onClick={() => setMenu(false)} className="text-sm font-semibold">Kenali tuan rumah</a></div><button className="md:hidden" onClick={() => setMenu(!menu)} aria-label="Menu">{menu ? <X /> : <Menu />}</button></nav>
    {notice && <div className="container mx-auto px-5"><div className="rounded-xl border border-[#b6d6c9] bg-[#e6f3ec] px-4 py-3 text-sm font-medium">{notice}</div></div>}
    <section id="top" className="container mx-auto grid items-center gap-10 px-5 pb-20 pt-10 md:grid-cols-[1.05fr_.95fr] md:pt-20"><div><p className="mb-5 flex items-center gap-2 text-sm font-bold uppercase tracking-[.18em] text-[#ba7625]"><Sparkles size={16} /> Jalan-jalan yang menumbuhkan</p><h1 className="max-w-2xl text-5xl font-black leading-[.98] tracking-[-.05em] md:text-7xl">Pergi lebih jauh.<br /><span className="text-[#d99838]">Pulang membawa dampak.</span></h1><p className="mt-7 max-w-lg text-lg leading-8 text-[#5c706b]">Ekowisata yang menghubungkan keindahan pegunungan, masa depan anak, dan kekuatan ibu lokal dalam satu perjalanan.</p><a href="#journeys" className="mt-8 inline-flex items-center gap-3 rounded-full bg-[#174e47] px-6 py-3.5 font-bold text-white shadow-lg shadow-[#174e47]/20">Temukan perjalanan <ArrowRight size={18} /></a></div><div className="relative overflow-hidden rounded-[2rem] bg-[#174e47] p-7 text-white md:min-h-[420px]"><div className="absolute -right-10 -top-10 h-48 w-48 rounded-full bg-[#e5a94c] opacity-90" /><div className="absolute bottom-0 right-0 h-56 w-56 rounded-tl-full bg-[#2d7664]" /><div className="relative flex h-full flex-col justify-between"><div className="flex items-center justify-between"><span className="rounded-full bg-white/10 px-3 py-1 text-xs font-semibold">Dampak nyata · 2026</span><HeartHandshake className="text-[#f4c978]" /></div><div className="mt-36"><p className="text-sm text-[#b6d6c9]">Dana pendidikan terkumpul</p><p className="mt-1 text-4xl font-black">{money(totalImpact)}</p><p className="mt-3 max-w-xs text-sm leading-6 text-white/70">Dari setiap booking, dana mengalir ke kebutuhan yang paling berarti.</p></div></div></div></section>
    <section className="border-y border-[#dfe5dc] bg-white"><div className="container mx-auto grid gap-6 px-5 py-9 md:grid-cols-3"><div className="flex gap-4"><Leaf className="shrink-0 text-[#d99838]" /><div><h3 className="font-bold">Ekowisata berakar</h3><p className="mt-1 text-sm leading-6 text-[#70817c]">Jelajah alam tanpa meninggalkan jejak buruk.</p></div></div><div className="flex gap-4"><BookOpen className="shrink-0 text-[#d99838]" /><div><h3 className="font-bold">Pendidikan fleksibel</h3><p className="mt-1 text-sm leading-6 text-[#70817c]">Alokasi mengikuti kebutuhan sekolah hari ini.</p></div></div><div className="flex gap-4"><Users className="shrink-0 text-[#d99838]" /><div><h3 className="font-bold">Ibu memimpin</h3><p className="mt-1 text-sm leading-6 text-[#70817c]">Keahlian lokal menjadi penghidupan bermartabat.</p></div></div></div></section>
    <section id="journeys" className="container mx-auto px-5 py-20"><div className="mb-10 flex items-end justify-between"><div><p className="text-sm font-bold uppercase tracking-[.16em] text-[#ba7625]">Perjalanan pilihan</p><h2 className="mt-2 text-3xl font-black tracking-tight md:text-4xl">Temui sisi lain pegunungan</h2></div><span className="hidden text-sm text-[#70817c] md:block">{packages.length || 2} pengalaman · low-data friendly</span></div><div className="grid gap-5 md:grid-cols-2">{packages.map((item) => <article key={item.id} className="group rounded-3xl border border-[#dfe5dc] bg-white p-6 transition hover:-translate-y-1 hover:shadow-xl"><div className={`mb-8 flex h-44 items-end rounded-2xl p-5 ${item.accent === "teal" ? "bg-[#c7e0d4]" : "bg-[#f4dfb6]"}`}><div className="flex w-full items-center justify-between"><span className="rounded-full bg-white/80 px-3 py-1 text-xs font-bold">{item.type}</span><Mountain className="text-[#174e47]" size={38} /></div></div><div className="flex items-start justify-between gap-4"><div><h3 className="text-xl font-extrabold">{item.title}</h3><p className="mt-2 text-sm text-[#70817c]">{item.location} · {item.duration}</p></div><p className="whitespace-nowrap font-black text-[#ba7625]">{money(item.price)}</p></div><p className="mt-4 text-sm leading-6 text-[#5c706b]">{item.description}</p><button onClick={() => setModal(item)} className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-[#174e47] px-4 py-3 font-bold text-white">Booking sekarang <ArrowRight size={16} /></button></article>)}</div></section>
    <section id="impact" className="bg-[#174e47] text-white"><div className="container mx-auto grid gap-12 px-5 py-20 md:grid-cols-[.8fr_1.2fr] md:items-center"><div><p className="text-sm font-bold uppercase tracking-[.16em] text-[#f4c978]">Impact tracker publik</p><h2 className="mt-3 text-4xl font-black tracking-tight">Setiap rupiah punya arah.</h2><p className="mt-5 max-w-sm leading-7 text-white/65">Transparan per kategori, karena kebutuhan anak pegunungan tidak pernah hanya satu.</p><div className="mt-8 flex items-center gap-3 text-sm font-semibold"><ShieldCheck className="text-[#f4c978]" /> Alokasi tercatat otomatis saat booking</div></div><div className="space-y-5">{totals.map((item, index) => <div key={item.category}><div className="mb-2 flex justify-between text-sm"><span>{item.category}</span><strong>{money(item.total)}</strong></div><div className="h-2 rounded-full bg-white/15"><div className="h-full rounded-full bg-[#e5a94c]" style={{ width: `${Math.max(16, Math.min(100, item.total / Math.max(totalImpact, 1) * 100))}%` }} /></div></div>)}</div></div></section>
    <section id="hosts" className="container mx-auto px-5 py-20"><div className="mb-10"><p className="text-sm font-bold uppercase tracking-[.16em] text-[#ba7625]">Tuan rumah kami</p><h2 className="mt-2 text-3xl font-black tracking-tight md:text-4xl">Cerita lokal, keahlian nyata</h2></div><div className="grid gap-5 md:grid-cols-2">{hosts.map((host) => <div key={host.id} className="flex gap-5 rounded-3xl border border-[#dfe5dc] bg-white p-6"><div className="grid h-16 w-16 shrink-0 place-items-center rounded-2xl bg-[#f4dfb6] text-2xl font-black text-[#ba7625]">{host.name?.slice(4, 5) || "M"}</div><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-extrabold">{host.name}</h3><span className="flex items-center gap-1 text-xs font-bold text-[#ba7625]"><Star size={13} fill="currentColor" /> {host.rating}</span></div><p className="mt-1 text-xs font-semibold text-[#70817c]">{host.location}</p><p className="mt-3 text-sm leading-6 text-[#5c706b]">“{host.story}”</p><div className="mt-4 flex flex-wrap gap-2">{(host.skills || []).map((skill) => <span key={skill} className="rounded-full bg-[#e6f3ec] px-3 py-1 text-xs font-semibold">{skill}</span>)}</div><p className="mt-4 flex items-center gap-2 text-xs font-bold text-[#174e47]"><HeartHandshake size={14} /> {money(host.impact_total)} dana pendidikan dari host ini</p></div></div>)}</div></section>
    <footer className="border-t border-[#dfe5dc] bg-white"><div className="container mx-auto flex flex-col gap-4 px-5 py-8 text-sm text-[#70817c] md:flex-row md:items-center md:justify-between"><span className="font-bold text-[#174e47]">MountainHarmony</span><span>Perjalanan kecil. Perubahan yang panjang.</span><span>© 2026 · Ekosistem lokal yang tumbuh bersama</span></div></footer>
    {modal && <div className="fixed inset-0 z-30 grid place-items-center bg-[#173f3a]/60 p-5"><form onSubmit={book} className="w-full max-w-md rounded-3xl bg-white p-7 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-[#ba7625]">Konfirmasi perjalanan</p><h2 className="mt-2 text-2xl font-black">{modal.title}</h2></div><button type="button" onClick={() => setModal(null)} aria-label="Tutup"><X /></button></div><label className="mt-7 block text-sm font-bold">Nama Anda<input required value={form.guest_name} onChange={(e) => setForm({ ...form, guest_name: e.target.value })} className="mt-2 w-full rounded-xl border border-[#dfe5dc] px-4 py-3 outline-none focus:ring-2 focus:ring-[#e5a94c]" placeholder="Nama lengkap" /></label><div className="mt-4 grid grid-cols-2 gap-3"><label className="text-sm font-bold">Jumlah orang<input type="number" min="1" value={form.guest_count} onChange={(e) => setForm({ ...form, guest_count: e.target.value })} className="mt-2 w-full rounded-xl border border-[#dfe5dc] px-4 py-3" /></label><label className="text-sm font-bold">Tanggal<input type="date" value={form.travel_date} onChange={(e) => setForm({ ...form, travel_date: e.target.value })} className="mt-2 w-full rounded-xl border border-[#dfe5dc] px-4 py-3" /></label></div><div className="mt-5 rounded-xl bg-[#e6f3ec] p-4 text-sm"><span>Total perjalanan</span><strong className="float-right">{money(modal.price * (Number(form.guest_count) || 1))}</strong><p className="mt-2 text-xs text-[#5c706b]">Alokasi pendidikan akan dibuat otomatis per kategori aktif.</p></div><button className="mt-5 w-full rounded-xl bg-[#174e47] py-3.5 font-bold text-white">Konfirmasi booking</button></form></div>}
  </main>;
}